import { Alert, Snackbar } from "@mui/material"
import { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useAuthContext } from "../lib/AuthContext"
import styles from '../styles/Home.module.css'

const Index: NextPage = () => {
  const { user } = useAuthContext()
  const isLoggedIn = !!user

  return (
    <>
      <Snackbar
          open={!isLoggedIn}
          anchorOrigin={{ vertical: "top", horizontal: "center" }}
          autoHideDuration={3000}
          key={"top" + "center"}
        >
          <Alert severity="warning">ログインしてください</Alert>
        </Snackbar>
      <Snackbar
        open={isLoggedIn}
        anchorOrigin={{ vertical: "top", horizontal: "center" }}
        autoHideDuration={3000}
        key={"top" + "center"}
      >
        <Alert severity="warning">
          既にログインしています
        </Alert>
      </Snackbar>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div><Link href={"./signup"}>新規登録</Link></div>
        <div><Link href={"./signin"}>ログイン</Link></div>
      </div>
    </>
  )
}

export default Index
